import numpy as np
import pandas as pd

'''
Tips：
Calculate the overlap based on the data generated by： Highly uncertain samples/1_Data_Production.py
'''

# Calculate overlap：
def overlap_coefficient(set1, set2):
    intersection_size = len(set1.intersection(set2))
    union_size = len(set1) + len(set2) - intersection_size
    if union_size == 0:
        return 0

    overlap_coeff = intersection_size / union_size
    return overlap_coeff

A = []
for i in range(10):
    # Replace it with your file path
    MCD_Point = np.load('/media/highuncertainty/NEW_Per20/MCD_L_' + str(i+1) + '.npy')
    DEs_Point = np.load('/media/highuncertainty/NEW_Per20/DEs_L_' + str(i+1) + '.npy')

    A.append(overlap_coefficient(set(MCD_Point), set(DEs_Point)))
    print('L',str(i+1),'_overlap:',overlap_coefficient(set(MCD_Point), set(DEs_Point)))

import matplotlib.pyplot as plt

x = [1,2,3,4,5,6,7,8,9,10]
fig, ax1 = plt.subplots()
# fig.set_size_inches(26,6)
ax1.plot(x,A,label='traj',marker='o',color='b')
plt.show()